// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using Veeya.Persistence;

namespace Veeya.Migrations
{
    [DbContext(typeof(VeeyaDbContext))]
    [Migration("20170923123012_AddInvestor")]
    partial class AddInvestor
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Veeya.Models.Investor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email_Address")
                        .IsRequired();

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("Phone_Number")
                        .IsRequired();

                    b.HasKey("id");

                    b.ToTable("Investors");
                });

            modelBuilder.Entity("Veeya.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AddressName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int>("WholesalerId");

                    b.HasKey("Id");

                    b.HasIndex("WholesalerId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("Veeya.Models.Wholesaler", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("id");

                    b.ToTable("Wholesalers");
                });

            modelBuilder.Entity("Veeya.Models.Property", b =>
                {
                    b.HasOne("Veeya.Models.Wholesaler", "Wholesaler")
                        .WithMany("Properties")
                        .HasForeignKey("WholesalerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
